### ISSUE TITLE
Print orientation of Gas Spring Holder L/R

### ISSUE THREAD

**Issue by bdistin** [Gi7mo/VoronBedHinge#1]
I printed without changing the orientation but Found the mounting was weak along layer lines. It would be better orientated with the flat side down (the side that goes against the extrusion) like how one of your photos shows instead.

**Comment by Gi7mo** [comment]
thanks for your feedback
printing it the other way around was my first intention too, but it broke after a few days
it broke at 90° link from extrusion to gaspring holder

oriented like in this repo, it holds up for a few month for me
